### ISSUE TITLE
PHP Notice - Undefined variable: singles

### ISSUE THREAD

**Issue by al-bglhk** [engram-design/ExpandedSingles#25]
### Description
I am getting thrown a ` PHP Notice – yii\base\ErrorException ` whenever I create a new Entry i.e. Blog Post.

It breaks because $single isn't defined outside the for-loop. And then you're accessing the variable-on-the-fly outside of the loop. If there are no singles, the variable fails.

### Steps to reproduce

1. Install and enable `verbb/expanded-singles:1.0.9` plugin
2. Create a new Entry.

### Additional info

- Plugin version: 1.0.9
- Craft version: 3.4.8

### Suggested Action
Declare the $single variable before the loop. Like this diff https://gist.github.com/al-bglhk/3a80c015203a0b72bd5b4b4e11f2a059

**Comment by engram-design** [comment]
Not sure how I missed that, but thanks! Fixed in [1.0.10](https://github.com/verbb/expanded-singles/releases/tag/1.0.10)

**Comment by al-bglhk** [comment]
The problem is still there. the `createSectionedSinglesList` method still misses the $singles declaration.

<img width="889" alt="image" src="https://user-images.githubusercontent.com/61268121/75529493-767bdf80-5a4e-11ea-8dfb-4e859f9a8180.png">

**Comment by engram-design** [comment]
Fixed in [1.0.11](https://github.com/verbb/expanded-singles/releases/tag/1.0.11)

**Comment by al-bglhk** [comment]
Verified. Thank you!
